### ISSUE TITLE
Info about releasing a README.md file

### ISSUE THREAD

**Issue by gsilano** [OPT4SMART/crazychoir#1]
Hi there! Great package. I saw the paper on ArXiv. When do you expect to have a detailed README.md file with the installation instructions and some examples? Thanks!

**Comment by andrea-testa** [comment]
Hi, thank you for your interest! We will provide more details soon, check it out in the next days!

**Comment by andrea-testa** [comment]
Hi, we released a detailed installation guide and some examples to be run. In the next days, we will provide a detailed description on the usage of the package. Thanks again for your support!
