### ISSUE TITLE
Crazyflie takeoff but drop and down in a vibration phenomenon

### ISSUE THREAD

**Issue by cbDragon** [OPT4SMART/crazychoir#12]
Hi guys, with your great help, I finally switched the Vicon to my own motion capture. Now I try to execute the single tracking launch program. However, when start the 'takeoff' buttun in the GUI, the crazyflie try to hover in the given altitude but failed in a drop and down with vibration phenomenon, here is the video [https://youtu.be/tCmIzYS04FM](url).
I make a few changes of the source code, the most important thing is that I delete the ''self.check_safety_area()" in the cmd_sender function cause only in this way can the cf fly properly. 
I wonder if the vibration phenomenon relate to some parameters which set up improperly in the controller, such as the quadropter's weight. Do you have the same phenomenon before? It's a great appreciate to give me some ideal solutions to figure out the problem, thanks!

**Comment by andrea-testa** [comment]
Hi there, thank you for reaching out. Indeed, this behavior is related to some controller parameters. I would decrease a little bit the proportional gain. As for the safety area, we changed it in our latest update so that it will not give any problem. Let us know if you are able to fly!

**Comment by cbDragon** [comment]
> Hi there, thank you for reaching out. Indeed, this behavior is related to some controller parameters. I would decrease a little bit the proportional gain. As for the safety area, we changed it in our latest update so that it will not give any problem. Let us know if you are able to fly!

Great!!! I decrease the `FlatnessPositionCtrl` K_p and K_v parameters, now it seems work well!! I will try to figure out the optimal parameters of my motion capture environment. Thanks a lot!
