### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mwlock** [OPT4SMART/crazychoir#13]
Hey all !

I am facing the following error when running ```colcon build --symlink-install```

For context, I am running ROS humble on Ubuntu 22.04

```
CMake Error at /opt/ros/humble/share/ament_cmake_python/cmake/ament_python_install_package.cmake:106 (add_custom_target):
  add_custom_target cannot create target
  "ament_cmake_python_symlink_choirbot_interfaces" because another target
  with the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/matt/crazychoir_ws/src/crazychoir/ChoiRbot/choirbot_interfaces".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  /opt/ros/humble/share/ament_cmake_python/cmake/ament_python_install_package.cmake:39 (_ament_cmake_python_install_package)
  CMakeLists.txt:18 (ament_python_install_package)


CMake Error at /opt/ros/humble/share/ament_cmake_python/cmake/ament_python_install_package.cmake:141 (add_custom_target):
  add_custom_target cannot create target
  "ament_cmake_python_build_choirbot_interfaces_egg" because another target
  with the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/matt/crazychoir_ws/src/crazychoir/ChoiRbot/choirbot_interfaces".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  /opt/ros/humble/share/ament_cmake_python/cmake/ament_python_install_package.cmake:39 (_ament_cmake_python_install_package)
  CMakeLists.txt:18 (ament_python_install_package)
```

Cheers!

**Comment by matthew-william-lock** [comment]
Apparently ```ament_python_install_package``` and ```rosidl_generate_interfaces``` cannot be run in the same package.... Nobody else faced this issue? https://github.com/ros2/rosidl_python/issues/141

**Comment by dbortoluzzi** [comment]
I think the project doesn't support ROS2 Humble at the moment. I have same your problems some months ago.

**Comment by lorenzopichierri** [comment]
Hi [matthew-william-lock](https://github.com/matthew-william-lock)! As [dbortoluzzi](https://github.com/dbortoluzzi) suggested, the project runs on ROS 2 Foxy. However, you are welcome to submit pull requests to the [humble-devel branch](https://github.com/OPT4SMART/crazychoir/tree/humble-devel) if you have any updates or improvements to contribute. Your input is appreciated, and feel free to reach out if you have any questions or need further clarification!
