### ISSUE TITLE
Webots Simulation Performance/Realism

### ISSUE THREAD

**Issue by matthew-william-lock** [OPT4SMART/crazychoir#14]
I have a general question regarding the simulation performance in Webots.

When I run the given example I find the control somewhat unstable and unpredictable.... Please take a look at the attached video for an example. What is the expected simulation performance?

https://github.com/OPT4SMART/crazychoir/assets/53016036/733f4fa7-8478-4b20-9d20-cb4b10391f1c

**Comment by lorenzopichierri** [comment]
Hi [matthew-william-lock](https://github.com/matthew-william-lock)!

Could you please provide information about your workstation configuration (RAM, CPU, GPU, etc.)? Because the  performance issues can be related to this.
