### ISSUE TITLE
Using Vrpn's motion capture data in position_getter.py?

### ISSUE THREAD

**Issue by Xuxxuuu** [OPT4SMART/crazychoir#16]
Hi!
Your work is great! I have currently completed the installation of Crazychoir, but I'm having some issues with the configuration process and it would be great if you could provide some guidance!

Our motion capture type is Nokov, which is capable of reading motion capture data from Vrpn in ros-topic form like Vicon. Would it be possible to use data from Vrpn in position_getter.py instead of from ros2-vicon-receiver, especially in a swarm scenario? What possible work needs to be done for such a change?

**Comment by lorenzopichierri** [comment]
Solved by [Xuxxuuu](https://github.com/Xuxxuuu).
