### ISSUE TITLE
Crazyflies are unstable at takeoff

### ISSUE THREAD

**Issue by ctab-0120** [OPT4SMART/crazychoir#17]
Hi! I am trying to use the Webots simulator, specifically the formation control simulation. I am able to start the simulation correctly but when I click on takeoff on the gui interface, the drones (usually 2 out of 4) start oscillating back and forth and eventually crash. I tried to play with some of the parameters but I was not able to fix this issue. Any ideas of what I could be doing wrong?

**Comment by lorenzopichierri** [comment]
Hi [ctab-0120](https://github.com/ctab-0120)!

Thank you for your interest in our toolbox, and I apologize for the delayed response. It seems the unstable behavior you're experiencing is related to a recent update in the Bitcraze firmware, which we haven't fully understood yet. However, we have solved this issue by using an older version of the firmware.

Please follow the new [instructions](https://github.com/OPT4SMART/crazychoir/tree/master/docker) using Docker, as it simplifies the installation and execution of our examples. We will also upload a tutorial video soon on writing distributed optimization algorithms for multi-drone applications from scratch.

Best,
Lorenzo
