### ISSUE TITLE
Crazyflie take off and fall immediately

### ISSUE THREAD

**Issue by Xuxxuuu** [OPT4SMART/crazychoir#18]
Hi! Your work is really great!! With your help, I finally managed to use NOKOV as the motion capture type. Now I run the tracking_vicon.launch.py（get pose and orientation from NOKOV）and start the takeoff button in GUI. Crazyflie takes off and falls immediately while it seems like turn over. I use a video link to show this phenomenon.  I am certain that the crazyflie has sufficient battery and the propellers are intact.
 I also make a few changes in the source code, the most important is that I also delete the ''self.check_safety_area()" in order to run the launch file successfully. Picture below is the roslaunch result, which I think there is no mistake.
 It would be great if you could provide some guidance!
 crazyflie fall video：https://www.youtube.com/shorts/Spq0xaM-fcg
![roslaunch](https://github.com/OPT4SMART/crazychoir/assets/161097297/ba6e38cc-29e7-43f4-ba42-8fb00cde2279)

**Comment by lorenzopichierri** [comment]
Hi [Xuxxuuu](https://github.com/Xuxxuuu)!

could you show me a 'ros2 topic list'?

Best,
Lorenzo
