### ISSUE TITLE
help with velocity control

### ISSUE THREAD

**Issue by Sankowitch** [OPT4SMART/crazychoir#19]
Hello, sorry for bothering you, but Ive run into some problems implementing velocity control, so to publish to each agents its own set of velocities. 
I was trying to modify formation control to work with velocities instead of accelerations. 
So my question would be how should I implement it?
Maybe you can give me some advice like how to just publish some random velocity to all agents just to see if it works. 

Thanks in advance.

**Comment by lorenzopichierri** [comment]
Hi @Sankowitch,

Thank you for your interest in our toolbox!

To implement an example using velocity control, I recommend starting with [this example](https://github.com/OPT4SMART/crazychoir/blob/master/crazychoir_examples/launch/aggregative_webots.launch.py). In this example, we implement a distributed strategy that generates location setpoints, which are then used as reference inputs for the velocity controller, implemented [here](https://github.com/OPT4SMART/crazychoir/blob/master/crazychoir/crazychoir/controller/velocity_ctrl.py).

If you need further suggestions, feel free to ask!

Best,
Lorenzo
