### ISSUE TITLE
Complie error for colcon build --symlink-install

### ISSUE THREAD

**Issue by LiuQiangOpenMind** [OPT4SMART/crazychoir#4]
My OS is Ubuntu is 20.04, and I have installed ROS2 foxy, webbot2022a and python3.10. The default version of python is 3.10, but I have come aross with these errors. Would someone give me the solution for these?

Finished <<< webots ros2 core [1.41s] Starting >>> webots ros2 mavic Starting >>> webots ros2 tesla Finished <<< choirbot [1.47s] Starting >>> crazychoir
Starting >>> choirbot examples.. stderr: webots rosz driver
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message): **Could NOT find PythonLibs: Found unsuitable version "3.8.10", but required is exact version "3.10"(found /usr/lib/x86 64-linux-gnu/libpython3.8.so) Call Stack (most recent call first):
/usr/share/cmake-3.16/Modules/FindPackageHandleStandardArqs.cmake:391 ( FPHSA FAILURE MESSAGE)/usr/share/cmake-3.16/Modules/FindPythonLibs.cmake:310 (FIND PACKAGE HANDLE STANDARD ARGS) CMakeLists.txt:39 (find package)**
Failed	<<< webots ros2 driver [2.67s, exited with code 1]	
Aborted	<<< choirbot examples [0.65s]	
Aborted	<<< crazychoir [1.02s]	
Aborted	<<< webots_ros2_mavic [1.66s]	
Aborted	<<< webots ros2 tesla [1.72s]	
Summary: 
7 packages finished [12.8s]1 package failed: webots ros2 driver
4 packages aborted: choirbot examples crazychoir webots ros2 mavic webots ros2 tesla2 packages had stderr output: webots ros2 core webots ros2 driver
8 packages not processed

**Comment by lorenzopichierri** [comment]
Hi [LiuQiangOpenMind](https://github.com/LiuQiangOpenMind)! Thank you for reaching out. The problem seems to be the python version. Have you tried to use Python 3.8?
